spring.application.name=place-routes
server.port=${PORT}

##MongoDB
#spring.data.mongodb.uri=mongodb://mongodb-server:27017/routes
spring.data.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOSTNAME}/routes?retryWrites=true&w=majority&appName=Cluster0

##Redis Cache
spring.data.redis.host=${REDIS_HOSTNAME}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.username=${REDIS_USERNAME}

##Api
api.weather=${API_WEATHER}